services:
  db:
    image: mysql
    restart: always
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "mysql -u $$MYSQL_USER -p$$MYSQL_PASSWORD -e \"SHOW TABLES IN $$MYSQL_DATABASE;\"" ]
      interval: 5s
      retries: 10

    # In case your computer already has MySQL or MariaDB installed, or both
    # and assuming you are using ports 3306 and 3307, I will bind the local port for accessing the MySQL container to port 3308.
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - ./backend/prod.env
    command: /bin/sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
volumes:
  mysql_data:
